# warpName:
#   world: world
#   x: 0.0
#   y: 0.0
#   z: 0.0
#   yaw: 0.0
#   pitch: 0.0

warps: {}

# blocklinks: store block locations mapped to warp names
# Example key: "world;x;y;z"
blocklinks: {}
